import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Trash2, Edit2 } from 'lucide-react';
import { Card, CardBody } from '../common/Card';
import { Button } from '../common/Button';
export function StoryCard({ story, onEdit, onDelete }) {
    const artefactCount = story.artefacts.length;
    const emailCount = story.artefacts.filter((a) => a.type === 'email').length;
    const imCount = story.artefacts.filter((a) => a.type === 'im').length;
    const lockedCount = story.artefacts.filter((a) => a.locked).length;
    const conditionCount = story.artefacts.filter((a) => a.releaseTriggers && a.releaseTriggers.length > 0).length;
    const lastModified = new Date(story.modified).toLocaleDateString();
    return (_jsx(Card, { className: "hover:shadow-md transition-shadow", children: _jsxs(CardBody, { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900", children: story.title }), _jsx("p", { className: "text-sm text-gray-600 mt-1", children: story.description || 'No description' })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 pt-2 border-t border-gray-200", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-600 uppercase tracking-wide", children: "Artefacts" }), _jsx("p", { className: "text-xl font-bold text-gray-900", children: artefactCount })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-600 uppercase tracking-wide", children: "Author" }), _jsx("p", { className: "text-sm font-medium text-gray-900 truncate", children: story.author })] })] }), _jsxs("div", { className: "grid grid-cols-4 gap-2 text-center text-sm", children: [_jsxs("div", { className: "bg-blue-50 rounded p-2", children: [_jsx("p", { className: "text-xs text-gray-600", children: "Email" }), _jsx("p", { className: "font-semibold text-gray-900", children: emailCount })] }), _jsxs("div", { className: "bg-purple-50 rounded p-2", children: [_jsx("p", { className: "text-xs text-gray-600", children: "IM" }), _jsx("p", { className: "font-semibold text-gray-900", children: imCount })] }), _jsxs("div", { className: "bg-red-50 rounded p-2", children: [_jsx("p", { className: "text-xs text-gray-600", children: "Locked" }), _jsx("p", { className: "font-semibold text-gray-900", children: lockedCount })] }), _jsxs("div", { className: "bg-yellow-50 rounded p-2", children: [_jsx("p", { className: "text-xs text-gray-600", children: "Gated" }), _jsx("p", { className: "font-semibold text-gray-900", children: conditionCount })] })] }), _jsxs("div", { className: "text-xs text-gray-500 pt-2 border-t border-gray-200", children: ["Modified ", lastModified, " \u2022 v", story.version] }), _jsxs("div", { className: "flex gap-2 pt-2", children: [_jsxs(Button, { size: "sm", variant: "outline", className: "flex-1", onClick: () => onEdit(story), children: [_jsx(Edit2, { className: "w-4 h-4 mr-2" }), "Edit"] }), _jsxs(Button, { size: "sm", variant: "destructive", className: "flex-1", onClick: () => onDelete(story.id), children: [_jsx(Trash2, { className: "w-4 h-4 mr-2" }), "Delete"] })] })] }) }));
}
